language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-26.0.2
    - platform-tools
    - android-26
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

script:
  ./gradlew checkstyle pmd build test